[platformio]
src_dir = src

; Shared settings inherited by every [env:...] section below.
[env]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub

[env:master]
build_src_filter = +<*> -<slave.cpp>
upload_port = COM10
monitor_port = COM10

[env:slave]
build_src_filter = +<*> -<master.cpp>
upload_port = COM4
monitor_port = COM4