[platformio]
src_dir = src
default_envs = master

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub

[env:master]
build_src_filter = +<Master esp32.cpp>
board_build.partitions = huge_app.csv

[env:slave]
build_src_filter = +<Slave esp32.cpp>